import type { Metadata } from "next";
import "./globals.css";
import Menu from '@/app/Menu';
import { sFetch } from '@/app/sfetch';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getData = async () => {
    return await sFetch<{id: string}[]>(`https://api.thecatapi.com/v1/images/search`, {
        next: {revalidate: 15},
    });
};

export default async  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const data = await getData();
    console.log('RootLayout',data![0].id)
  return (
    <html lang="en">
      <body
      >
      <Menu/>
          {children}
      </body>
    </html>
  );
}
