import type { Metadata } from "next";
import "./globals.css";
import Menu from '@/app/Menu';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 1000;
export const dynamic = 'force-static';

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
      <Menu/>
          {children}
      </body>
    </html>
  );
}
